ingress:
  enabled: true
  ingressClassName: traefik

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  hosts:
    - grafana.fazelshah.fun

  path: /
  pathType: Prefix

  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.fazelshah.fun

service:
  type: ClusterIP
  port: 443
  targetPort: 3000
