ingress:
  enabled: true
  ingressClassName: traefik

  hosts:
    - grafana.fazelshah.fun

  path: /
  pathType: Prefix

  tls:
    - hosts:
        - grafana.fazelshah.fun

service:
  type: ClusterIP
  port: 443
  targetPort: 3000
